version: '3'
services:
  front:
    build:
      context: ./front
    ports:
      - "4200:4200"
    depends_on:
      - api
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - my-network
networks:
  my-network: